apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab-namespace
stringData:
  gitlab.rb: |-
    gitlab_rails['gitlab_shell_ssh_port'] = 32222
    prometheus['monitor_kubernetes'] = false
    gitlab_rails['initial_root_password'] = "SENHA"
    external_url 'https://gitlab.<dominio.com.br>'
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    nginx['proxy_set_headers'] = {
      'X-Forwarded-Proto' => 'https',
      'X-Forwarded-Ssl' => 'on'
    }
    registry_external_url 'https://registry.<dominio.com.br>'
    gitlab_rails['registry_enabled'] = true
    registry_nginx['listen_port'] = 5050
    registry_nginx['listen_https'] = false
    registry_nginx['proxy_set_headers'] = {
      'X-Forwarded-Proto' => 'https',
      'X-Forwarded-Ssl' => 'on'
    }
