---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-claim
  namespace: gitlab-namespace
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-credentials-claim
  namespace: gitlab-namespace
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi